#'
#' The ASX20 (as of 16-06-2013):
#' AMP	AMP LIMITED	
#' ANZ	AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED	
#' BHP	BHP BILLITON LIMITED	
#' BXB	BRAMBLES LIMITED	
#' CBA	COMMONWEALTH BANK OF AUSTRALIA.	
#' CSL	CSL LIMITED	
#' MQG	MACQUARIE GROUP LIMITED	
#' NAB	NATIONAL AUSTRALIA BANK LIMITED	
#' NCM	NEWCREST MINING LIMITED	
#' ORG	ORIGIN ENERGY LIMITED	
#' QBE	QBE INSURANCE GROUP LIMITED	
#' RIO	RIO TINTO LIMITED	
#' STO	SANTOS LIMITED	
#' SUN	SUNCORP GROUP LIMITED	
#' TLS	TELSTRA CORPORATION LIMITED.	
#' WBC	WESTPAC BANKING CORPORATION	
#' WDC	WESTFIELD GROUP	
#' WES	WESFARMERS LIMITED	
#' WOW	WOOLWORTHS LIMITED	
#' WPL	WOODSIDE PETROLEUM LIMITED	

ASX20_constituents <- c("AMP", "ANZ", "BHP", "BXB", "CBA", "CSL", "MQG", "NAB", "NCM", "ORG", 
		"QBE", "RIO", "STO", "SUN", "TLS", "WBC", "WDC", "WES", "WOW", "WPL")


